import numpy as np

x = np.array([2, 4, 6, 8])
y = np.array([1, 2, 3, 4])
sum = np.add(x, y)
mul= np.multiply(x, y)
power = np.power(x, y)
div = np.divide(x, y)
sub = np.subtract(x, y)
mod = np.mod(x, y)
remain = np.remainder(x, y)
divmod = np.divmod(x, y)
abs = np.absolute([-1, -3, -4, -5])
print(sum)
print(mul)
print(power)
print(div)
print(sub)
print(mod)
print(remain)
print(divmod[0])
print(divmod[1])
print(abs)